[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libpq", "gcc"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn \"app:create_app()\" --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
